safe: true
lsi: false
pygments: true
markdown: kramdown

# Permalinks
permalink:        pretty

# Server
source:	./dev/jekyll
destination: ./dev/_pub
url: http://jnmarcus.github.io
encoding: UTF-8
include: ['.nojekyll']
exclude: ['node_modules', 'dev/styles/less', 'Gemfile', 'Gemfile.lock', 'README.md', 'package.json', 'Gruntfile.js', 'site', '.grunt']

# Setup
title:            'Jamie Marcus'
tagline:          'UX Designer, Front End Developer, Engineer'
description:      'Portfolio site for Jamie Marcus'

author:
  name:           'Jamie Marcus'

# paginate:         5

# Custom vars
# version:          1.0.0

github:
  repo:           https://github.com/jnmarcus/jnmarcus.github.io
  profile:		  https://github.com/jnmarcus