safe: true
lsi: false
pygments: true
markdown: kramdown

# source: .

source: .
# destination: _gh_pages
url: http://jnmarcus.github.io
encoding: UTF-8
exclude: ['node_modules', 'less', 'app', 'test', 'Gemfile', 'Gemfile.lock', 'README.md', 'package.json', 'package-old.json', 'Gruntfile.js', 'Gruntfile-old.js', 'custom-bootstrap.map', 'site']
